# Generated by Django 4.2.3 on 2023-08-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('CH', 'Chave'), ('CR', 'Cracha'), ('FO', 'Folha')], default='CH', max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
